name: Deploy blog

on:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install -r requirements.txt
    - name: Lint
      run: blog lint
    - if: ${{ github.ref == 'refs/heads/master' }}
      name: Deploy
      run: blog deploy
